insert into Sucursales (calle, numero, ciudad, estado) values ('Pankratz', 4957, 'Zentla', 'Aguascalientes');
insert into Sucursales (calle, numero, ciudad, estado) values ('Mesta', 99, 'Tepetzintla', 'Baja California');
insert into Sucursales (calle, numero, ciudad, estado) values ('Pearson', 35, 'Tangamandapio', 'Baja California Sur');
insert into Sucursales (calle, numero, ciudad, estado) values ('Warner', 79455, 'Ixtepec', 'Campeche');
insert into Sucursales (calle, numero, ciudad, estado) values ('Russell', 790, 'Vicente Guerrero', 'Coahuila de Zaragoza');
insert into Sucursales (calle, numero, ciudad, estado) values ('Sachs', 68, 'Calcahualco', 'Colima');
insert into Sucursales (calle, numero, ciudad, estado) values ('Lillian', '0860', 'Ixtapaluca', 'Chiapas');
insert into Sucursales (calle, numero, ciudad, estado) values ('Warner', '4922', 'Santiago Textitlán', 'Chihuahua');
insert into Sucursales (calle, numero, ciudad, estado) values ('Scofield', '36136', 'San Lorenzo Victoria', 'Ciudad de México');
insert into Sucursales (calle, numero, ciudad, estado) values ('Sheridan', '2', 'Etzatlán', 'Durango');
insert into Sucursales (calle, numero, ciudad, estado) values ('Ridge Oak', '864', 'San Martín Lachilá', 'Guanajuato');
insert into Sucursales (calle, numero, ciudad, estado) values ('High Crossing', '26224', 'Tlalixcoyan', 'Guerrero');
insert into Sucursales (calle, numero, ciudad, estado) values ('Kennedy', '7144', 'San Ildefonso Villa Alta', 'Hidalgo');
insert into Sucursales (calle, numero, ciudad, estado) values ('Warner', '34052', 'Sanahcat', 'Jalisco');
insert into Sucursales (calle, numero, ciudad, estado) values ('Bultman', '1991', 'Contla de Juan Cuamatzi', 'México');
insert into Sucursales (calle, numero, ciudad, estado) values ('Vahlen', '8', 'Muxupip', 'Michoacán de Ocampo');
insert into Sucursales (calle, numero, ciudad, estado) values ('2nd', '5', 'Santa María Nduayaco', 'Morelos');
insert into Sucursales (calle, numero, ciudad, estado) values ('Talmadge', '86425', 'Capulálpam de Méndez', 'Nayarit');
insert into Sucursales (calle, numero, ciudad, estado) values ('Huxley', '15', 'San Pedro Yeloixtlahuaca', 'Nuevo León');
insert into Sucursales (calle, numero, ciudad, estado) values ('Brentwood', '24', 'Tlapacoya', 'Oaxaca');
insert into Sucursales (calle, numero, ciudad, estado) values ('Village Green', '87597', 'Texcalyacac', 'Puebla');
insert into Sucursales (calle, numero, ciudad, estado) values ('Oriole', '62768', 'Tlalnepantla', 'Querétaro');
insert into Sucursales (calle, numero, ciudad, estado) values ('Stoughton', '0', 'San Juan Guichicovi', 'Quintana Roo');
insert into Sucursales (calle, numero, ciudad, estado) values ('Merrick', '6812', 'San Juan del Estado', 'San Luis Potosí');
insert into Sucursales (calle, numero, ciudad, estado) values ('Birchwood', '63', 'Venustiano Carranza', 'Sinaloa');
insert into Sucursales (calle, numero, ciudad, estado) values ('Stone Corner', '12', 'Tres Valles', 'Sonora');
insert into Sucursales (calle, numero, ciudad, estado) values ('Longview', '06103', 'Acatlán de Pérez Figueroa', 'Tabasco');
insert into Sucursales (calle, numero, ciudad, estado) values ('Muir', '40', 'Piaxtla', 'Tamaulipas');
insert into Sucursales (calle, numero, ciudad, estado) values ('Fieldstone', '49', 'Venado', 'Tlaxcala');
insert into Sucursales (calle, numero, ciudad, estado) values ('Marcy', '5', 'San Lucas', 'Veracruz');
insert into Sucursales (calle, numero, ciudad, estado) values ('Bowman', '83089', 'Kantunil', 'Yucatán');
insert into Sucursales (calle, numero, ciudad, estado) values ('Raven', '51103', 'Tecámac', 'Zacatecas');
insert into Sucursales (calle, numero, ciudad, estado) values ('Eugenia', '456', 'Benito Juárez', 'Ciudad de México');
insert into Sucursales (calle, numero, ciudad, estado) values ('Hovde', '945', 'Villa Guerrero', 'Durango');
insert into Sucursales (calle, numero, ciudad, estado) values ('NorthPort', '5842', 'Nazas', 'Baja California');
insert into Sucursales (calle, numero, ciudad, estado) values ('Knutson', '505', 'Coatecas Altas', 'Morelos');
insert into Sucursales (calle, numero, ciudad, estado) values ('Buhler', '2', 'Chigmecatitlán', 'México');
insert into Sucursales (calle, numero, ciudad, estado) values ('Bellgrove', '8451', 'Guadalajara', 'Jalisco');
insert into Sucursales (calle, numero, ciudad, estado) values ('Monument', '5', 'Venustiano Carranza', 'Ciudad de México');
insert into Sucursales (calle, numero, ciudad, estado) values ('Loftsgordon', '293', 'Santa Lucía Miahuatlán', 'Colima');
